server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /posts/create {
        proxy_pass http://posts-clusterip-srv:4000/posts/create;
    }

    location /posts {
        proxy_pass http://query-srv:4002/posts;
    }
}