services:
  event-bus-srv:
    build: 
      context: ./event-bus
    ports:
      - "4005:4005"
    restart: always

  posts-clusterip-srv:
    build: 
      context: ./posts
    ports:
      - "4000:4000"
    restart: always

  comments-srv:
    build: 
      context: ./comments
    ports:
      - "4001:4001"
    restart: always

  query-srv:
    build: 
      context: ./query
    ports:
      - "4002:4002"
    restart: always

  moderation-srv:
    build: 
      context: ./moderation
    ports:
      - "4003:4003"
    restart: always

  client-srv:
    build: 
      context: ./client
    restart: always

  ingress-proxy:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client-srv
      - posts-clusterip-srv
      - query-srv
      - comments-srv
