server {
    listen 80;

    location / {
        proxy_pass http://client-srv:80; 
    }

    location /posts/create {
        proxy_pass http://posts-clusterip-srv:4000/posts/create;
    }

    location /posts {
        proxy_pass http://query-srv:4002/posts;
    }

    location ~ ^/posts/[^/]+/comments {
        proxy_pass http://comments-srv:4001;
    }
}