# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  POSTS: posts-clusterip-srv
  CLIENT: client-srv
  COMMENTS: comments-srv
  MODERATION: moderation-srv
  EVENT: event-bus-srv
  QUERY: query-srv

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "Hello !"
    silent: true
  build-client:
    desc: Build Client images
    cmds:
      - docker build -t {{.CLIENT}} ./client
  build-comments:
    desc: Build Comments image
    cmds:
      - docker build -t {{.COMMENTS}} ./comments
  build-event-bus:
    desc: Build Event-Bus image
    cmds:
      - docker build -t {{.EVENT}} ./event-bus
  build-moderation:
    desc: Build Moderation image
    cmds:
      - docker build -t {{.MODERATION}} ./moderation
  build-posts:
    desc: Build Posts image
    cmds:
      - docker build -t {{.POSTS}} ./posts
  build-query:
    desc: Build Query image
    cmds:
      - docker build -t {{.QUERY}} ./query
  build-images:
    desc: Build all the Dockerfile
    cmds:
      - task: build-client
      - task: build-comments
      - task: build-event-bus
      - task: build-moderation
      - task: build-posts
      - task: build-query
  terminal:
    desc: Open a terminal in the client container
    cmds:
      - docker exec -it {{.CLI_ARGS}} bash
  reset-deploys:
    desc: delete and apply all project deploy
    cmds:
      - kubectl delete deploy client-dpl
      - kubectl delete deploy comments-dpl
      - kubectl delete deploy event-bus-dpl
      - kubectl delete deploy moderation-dpl
      - kubectl delete deploy posts-mongo-dpl
      - kubectl delete deploy query-dpl
      - kubectl delete deploy comments-mongo-dpl
      - kubectl delete deploy posts-clusterip-dpl
      - kubectl delete deploy query-mongo-dpl
      - kubectl apply -f .\\client\\k8s\\client.yml
      - kubectl apply -f .\\comments\\k8s\\comments.yml
      - kubectl apply -f .\\event-bus\\k8s\\event-bus.yml
      - kubectl apply -f .\\moderation\\k8s\\moderation.yml
      - kubectl apply -f .\\posts\\k8s\\posts.yml
      - kubectl apply -f .\\query\\k8s\\query.yml
      - kubectl apply -f .\\databases\\comments-mongo-dpl.yml
      - kubectl apply -f .\\databases\\posts-mongo-dpl.yml
      - kubectl apply -f .\\databases\\query-mongo-dpl.yml
